// Code generated by interfacer; DO NOT EDIT

package jiraclient

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"

	"github.com/andygrunwald/go-jira"
)

// Client is an interface generated for "github.com/andygrunwald/go-jira.Client".
type Client interface {
	Do(*http.Request, interface{}) (*jira.Response, error)
	GetBaseURL() url.URL
	NewMultiPartRequest(string, string, *bytes.Buffer) (*http.Request, error)
	NewMultiPartRequestWithContext(context.Context, string, string, *bytes.Buffer) (*http.Request, error)
	NewRawRequest(string, string, io.Reader) (*http.Request, error)
	NewRawRequestWithContext(context.Context, string, string, io.Reader) (*http.Request, error)
	NewRequest(string, string, interface{}) (*http.Request, error)
	NewRequestWithContext(context.Context, string, string, interface{}) (*http.Request, error)
}
